import { cell, table } from './catalog.js';
import { CAPABILITIES } from './facet-matrix.js';
import type { CapabilityGroup, Column } from './facet-matrix.js';

/**
 * The signature cards — one generated page per KIND of test, under
 * `skills/jterrazz-test/references/`, plus the fork table those cards branch
 * from.
 *
 * A card is what an agent reads before writing a test of that kind: where the
 * file goes, the line that builds the runner, every constructor option with its
 * default, every setup, every terminal action, every result accessor, and the
 * chapter that explains them. It is a PROJECTION, never authored: the lists come
 * from the facet declaration (`facet-matrix.ts`), so a method added to a facet
 * and forgotten here fails a meta-test rather than going quietly missing from
 * the page an agent trusts.
 *
 * Two owners, and the boundary between them is the point:
 *
 * - `facet-matrix.ts` owns WHICH capabilities a column has. Nothing here may
 *   add a name it does not declare, and {@link SIGNATURES} must cover every one
 *   it does ({@link uncoveredCapabilities}, {@link deadSignatures}).
 * - this module owns how each one READS — its signature and its one line — once
 *   for the whole vocabulary, because `.seed()` means the same thing on four
 *   facets and a per-card description would be four chances to disagree.
 */

/** The eight kinds a test can be, in the order the fork asks them. */
export const KINDS = [
    'module',
    'integration',
    'component',
    'website',
    'mobile',
    'api',
    'jobs',
    'cli',
] as const satisfies readonly Column[];

/** One kind of test — the column of the capability matrix it reads. */
export type Kind = (typeof KINDS)[number];

/** First-line header stamped on every generated card. */
export const CARD_HEADER = "<!-- GENERATED by 'npm run docs' — DO NOT EDIT -->";

/** Markers delimiting the generated fork table inside `docs/18-conventions.md`. */
export const FORK_START =
    '<!-- GENERATED:fork — do not edit by hand; run `npm run docs`. Source: src/lint/cards.ts -->';
export const FORK_END = '<!-- /GENERATED:fork -->';

/** One row of the fork: the question, and everything its answer fixes. */
type ForkRow = {
    constructor: string;
    kind: string;
    livesAt: string;
    project: string;
    question: string;
};

/**
 * The fork, in the order the questions are asked. The order is the decision:
 * a rendered page is a website spec even though it also answers HTTP, and a
 * module alone is the last row because every other question failed.
 */
export const FORK: ForkRow[] = [
    {
        constructor: '`specification.website()`',
        kind: 'website',
        livesAt: '`specs/website/<domain>/<aspect>.spec.ts`',
        project: '`website`',
        question: 'Does it render in a browser as a whole served page?',
    },
    {
        constructor: 'none — the `component` chain',
        kind: 'component',
        livesAt: '`<file>.test.tsx` beside `<file>.tsx`',
        project: '`component`',
        question: 'Does it render as a component (React, a DOM function, a hook)?',
    },
    {
        constructor: '`specification.mobile()`',
        kind: 'mobile',
        livesAt: '`specs/mobile/<domain>/<aspect>.spec.ts`',
        project: '`mobile`',
        question: 'Does it render on a simulator?',
    },
    {
        constructor: '`specification.api()`',
        kind: 'api',
        livesAt: '`specs/api/<domain>/<aspect>.spec.ts`',
        project: '`api`',
        question: 'Does it answer HTTP?',
    },
    {
        constructor: '`specification.jobs()`',
        kind: 'jobs',
        livesAt: '`specs/jobs/<domain>/<aspect>.spec.ts`',
        project: '`jobs`',
        question: 'Is it triggered by name, in-process?',
    },
    {
        constructor: '`specification.cli(bin)`',
        kind: 'cli',
        livesAt: '`specs/cli/<domain>/` (+ `<case>.spec.yaml`)',
        project: '`cli`',
        question: 'Is it a binary?',
    },
    {
        constructor: '`specification.integration()`',
        kind: 'integration',
        livesAt: '`specs/integration/<domain>/<aspect>.spec.ts`',
        project: '`integration`',
        question: 'Is it a module that needs a real service, or whose oracle is a golden?',
    },
    {
        constructor: 'none',
        kind: 'module',
        livesAt: '`<file>.test.ts` beside `<file>.ts`',
        project: '`unit`',
        question: 'Is it a module alone?',
    },
    {
        constructor: 'none',
        kind: 'repository suite',
        livesAt: '`specs/<family>/<aspect>.test.ts`',
        project: 'any name',
        question: 'Is it the repository itself — a suite over several apps?',
    },
];

/** How one capability reads: its call shape, and the one line that says what it does. */
type Signature = { line: string; signature: string };

/**
 * Every capability the cards render, said once. The key is the capability's
 * name in `facet-matrix.ts` — the two lists are held equal by a meta-test, in
 * both directions.
 */
export const SIGNATURES: Record<string, Signature> = {
    '.aria.yaml tree': {
        line: 'The accessibility outline of the surface — the golden a rendered thing wants, deterministic where a screenshot is not. Awaited on a component, where the capture crosses the browser seam; sync on a page',
        signature: "expect(result.tree).toMatch('<name>.aria.yaml')",
    },
    '.call()': {
        line: 'Calls the module, with the services it was handed; resolves to a `CallResult`',
        signature: '.call(({ db }) => repo(db.connectionString).find(id))',
    },
    '.clock()': {
        line: 'Pins `Date` for this chain — the one primitive for time',
        signature: ".clock('2026-03-04T09:30:00Z')",
    },
    '.console': {
        line: 'Every console message the page emitted, one `[type] text` line each',
        signature: 'result.console',
    },
    '.content': {
        line: 'The rendered text a reader sees — not the markup',
        signature: 'result.content',
    },
    '.delete()': { line: 'Sends `DELETE <path>`', signature: ".delete('/users/1')" },
    '.directory()': {
        line: 'A tree snapshot of one directory the run left behind',
        signature: ".directory('out')",
    },
    '.env()': {
        line: "The child process environment for this chain — `$WORKDIR` expands, `null` unsets; wins over the constructor's `defaults`",
        signature: ".env({ TZ: 'UTC' })",
    },
    '.alternates': {
        line: 'The `hreflang` alternates the document declares, by language',
        signature: 'result.alternates',
    },
    '.body': {
        line: 'The raw response body of a fetch, as a stream subject',
        signature: 'result.body',
    },
    '.canonical': {
        line: 'The canonical URL the document declares, or `null`',
        signature: 'result.canonical',
    },
    '.container()': {
        line: 'One container the run started, by name — its logs and its exec surface',
        signature: ".container('db')",
    },
    '.containerIds': {
        line: 'The ids of the containers the run left running, for a leak assertion',
        signature: 'result.containerIds',
    },
    '.error': {
        line: 'What the subject threw, as a subject of its own — a refusal is an answer',
        signature: 'result.error',
    },
    '.errors': {
        line: 'Console messages of type `error` only, plus any uncaught page error',
        signature: 'result.errors',
    },
    '.filesystem': {
        line: 'The whole working directory as one subject — the shape of what the run wrote',
        signature: 'result.filesystem',
    },
    '.exec()': {
        line: 'Runs the binary — the ONLY execution method (rule B2). Bare for no arguments',
        signature: ".exec('build --watch', { timeout, waitFor })",
    },
    '.exitCode': { line: 'The process exit code', signature: 'result.exitCode' },
    '.fetch()': {
        line: 'One raw HTTP exchange against the site — no browser, no scenario',
        signature: ".fetch('/robots.txt')",
    },
    '.file()': {
        line: 'One file in the working directory, as a stream subject',
        signature: ".file('out/report.json')",
    },
    '.fixture()': {
        line: "Copies a fixture tree into the run's working directory",
        signature: ".fixture('a-project')",
    },
    '.get()': { line: 'Sends `GET <path>`', signature: ".get('/users')" },
    '.head': {
        line: 'The parsed `<head>` — every meta, link and script the document declares',
        signature: 'result.head',
    },
    '.headers': {
        line: 'The response headers of a fetch, lower-cased',
        signature: 'result.headers',
    },
    '.headers()': {
        line: 'Request headers for this chain',
        signature: ".headers({ 'Accept-Language': 'fr' })",
    },
    '.html': {
        line: 'The mounted markup — the escape hatch for a class or an attribute',
        signature: 'result.html',
    },
    '.http exchange': {
        line: 'A complete request/response pair as a file: status line, header subset, body, tokens',
        signature: "expect(result.response).toMatch('user-created.http')",
    },
    '.intercept()': {
        line: 'Declares what the network answers, from contracts — strict from the first one (rule D7)',
        signature: '.intercept(contracts)',
    },
    '.json': {
        line: 'The body parsed as JSON — stdout for a binary, the response for a fetch',
        signature: 'result.json',
    },
    '.json body': {
        line: 'A JSON payload as a file, tokens resolved and keys compared',
        signature: "await expect(subject).toMatch('created.json')",
    },
    '.jsonLd': {
        line: 'The JSON-LD blocks the document carries, parsed',
        signature: 'result.jsonLd',
    },
    '.links': {
        line: 'Every anchor of the page, with its href and its accessible name',
        signature: 'result.links',
    },
    '.location': {
        line: 'The `Location` header of a redirect — never followed',
        signature: 'result.location',
    },
    '.meta()': { line: 'One meta tag by name or property', signature: "result.meta('og:title')" },
    '.open()': {
        line: 'Opens the app, optionally at a deep link, and runs the scenario before capturing',
        signature: ".open('news://events', async (visitor) => { … })",
    },
    '.post()': { line: 'Sends `POST <path>`', signature: ".post('/users', body)" },
    '.put()': { line: 'Sends `PUT <path>`', signature: ".put('/users/1', body)" },
    '.render()': {
        line: 'Mounts a React tree, or hands a DOM function a fresh container, and runs the scenario',
        signature: '.render(<X />, async (visitor) => { … })',
    },
    '.request()': {
        line: 'Sends the complete request written in a `_requests/*.http` file',
        signature: ".request('create-user.http')",
    },
    '.response': {
        line: 'The HTTP response — status, headers, body, matched against an `.http` golden',
        signature: 'result.response',
    },
    '.run()': {
        line: 'The BRIDGE door: runs a `<case>.spec.yaml` document and resolves with its last run, for the one assertion the grammar cannot say',
        signature: ".run('scaffold.spec.yaml')",
    },
    '.seed()': {
        line: 'Loads a `_seeds/*.sql` file into the named service before the action',
        signature: ".seed('users.sql')",
    },
    '.screen': {
        line: 'The device screen as a tree — the outline a golden pins',
        signature: 'result.screen',
    },
    '.status': {
        line: 'The HTTP status of the response, or of the document',
        signature: 'result.status',
    },
    '.stderr': { line: 'The error stream, as a stream subject', signature: 'result.stderr' },
    '.stdout': { line: 'The output stream, as a stream subject', signature: 'result.stdout' },
    '.table()': {
        line: 'The rows a service holds after the action — the oracle of anything that writes',
        signature: ".table('users', { database: 'main' })",
    },
    '.tree': {
        line: 'The accessibility tree of the surface — the outline a screen reader walks',
        signature: 'result.tree',
    },
    '.title': { line: 'The document title, as a stream subject', signature: 'result.title' },
    '.trigger()': {
        line: 'Triggers the job by NAME, the way the scheduler would',
        signature: ".trigger('daily-digest')",
    },
    '.txt stream': {
        line: 'A text stream as a file — stdout, stderr, a rendered body',
        signature: "await expect(subject).toMatch('help.txt')",
    },
    '.url': { line: 'The URL the page ended on, after every redirect', signature: 'result.url' },
    '.value': {
        line: 'What the call returned — a JSON accessor for an object, a text accessor for a string',
        signature: 'result.value',
    },
    '.viewport()': {
        line: 'The page size THIS render gets; the project size is restored at the end',
        signature: '.viewport({ height: 720, width: 1280 })',
    },
    '.visit()': {
        line: 'Renders the page in a real browser and runs the scenario before capturing',
        signature: ".visit('/', async (visitor) => { … })",
    },
    '.wrap()': {
        line: 'Wraps every render of THIS chain — a router stub, a provider one test needs',
        signature: '.wrap((ui) => <Router>{ui}</Router>)',
    },
    '{ frozen }': {
        line: 'Opts one fixture out of the update-mode rewrite — a negative fixture stays wrong on purpose',
        signature: "toMatch('refused.txt', { frozen: true })",
    },
    "toMatch('<name>')": {
        line: 'Compares the subject to the file of that name under `_expected/`, tokens resolved; `TEST_UPDATE=1` writes it',
        signature: "expect(subject).toMatch('<name>.<ext>')",
    },
    app: { line: 'The built app bundle the simulator installs', signature: 'app: string' },
    backend: {
        line: 'A stub backend started before the site, its URL injected into the child env',
        signature: "backend: { env: 'API_URL' }",
    },
    'clock()': {
        line: 'Pins `Date` (`clock.at`) or the scheduler too (`clock.run` + `clock.advance`), for the scope',
        signature: "using _ = clock.at('2026-03-04T09:30:00Z')",
    },
    defaults: {
        line: 'Environment applied to EVERY run of the binary; a chained `.env()` and a document `env:` win over it',
        signature: 'defaults?: Record<string, null | string>',
    },
    clock: {
        line: "The project's pinned `Date` — every render of the project starts there",
        signature: "clock: '2026-03-04T09:30:00Z'",
    },
    device: {
        line: 'Which simulator to resolve — by name, or by the platform version',
        signature: 'device: { name?, platform? }',
    },
    docker: {
        line: 'The compose stack this binary is run against, started with the runner',
        signature: "docker: { compose: './docker-compose.yml' }",
    },
    env: {
        line: 'Named environments the documents select by name (`env: staging`)',
        signature: "env: { staging: { API_URL: '…' } }",
    },
    external: {
        line: 'Cross-origin request policy for visits — blocked with a local server, allowed against a deployment',
        signature: "external: 'block'",
    },
    'intercept()': {
        line: 'The chain-less double: declares the network for the scope. `{ origin }` states what a relative request resolves against',
        signature: 'await using _ = await intercept(contracts, { origin })',
    },
    jobs: {
        line: 'The pipeline registry the trigger name is looked up in',
        signature: 'jobs: JobsRegistry',
    },
    locale: {
        line: "The project's locale — what `Intl` answers in every render",
        signature: "locale: 'en-US'",
    },
    'match.*': {
        line: 'The token vocabulary in code — the same families a golden writes as `{{token}}`',
        signature: 'expect(value).toStrictEqual({ id: match.uuid() })',
    },
    'mockOf()': {
        line: 'A typed double for an INJECTED port — deep by default, `{ deep: false }` for the flat proxy',
        signature: 'mockOf<Port>({ deep })',
    },
    root: {
        line: 'Project-root override (rule A9); auto-discovered from the calling file when absent',
        signature: "root: './apps/api'",
    },
    serve: {
        line: 'The processes a `<case>.spec.yaml` may name in its `serve:` list',
        signature: 'serve: { site: process({ command }) }',
    },
    server: {
        line: 'The app to start in this process — a Hono app, a fetch handler, a factory',
        signature: 'server: () => App',
    },
    services: {
        line: 'Named infrastructure the chain gets, isolated per worker and reset per chain',
        signature: 'services: { main: postgres() }',
    },
    timeouts: {
        line: 'How long a device is given to launch, to settle and to find an element',
        signature: 'timeouts: { launch: 60_000 }',
    },
    timezone: {
        line: "The project's timezone — what every render's `Date` is read in",
        signature: "timezone: 'UTC'",
    },
    'toMatchRows()': {
        line: 'Compares a table to a column list and one array of cells per row',
        signature: "expect(result.table('users')).toMatchRows({ columns, rows })",
    },
    transform: {
        line: "Normalises the binary's output before it is asserted — a last resort for what tokens cannot say",
        signature: 'transform: (text) => text.replaceAll(…)',
    },
    url: {
        line: 'An already-running deployment to drive instead of starting one (XOR with `server`, rule A11)',
        signature: "url: 'https://staging.site.test'",
    },
    viewport: {
        line: "The project's page size — the frame every render of it starts in",
        signature: 'viewport: { height: 720, width: 1280 }',
    },
    vite: {
        line: 'The Vite config the page is built with — a path, an object, or a promise of one',
        signature: "vite: './vite.config.ts'",
    },
    wrap: {
        line: "The project's frame around every render — a module path whose default export is `(ui) => ReactNode`",
        signature: "wrap: './src/providers.tsx'",
    },
};

/** The groups a card renders, and the heading each one gets. */
const SECTIONS: { group: CapabilityGroup; title: string }[] = [
    { group: 'Constructor option', title: 'Options' },
    { group: 'Setup', title: 'Setups (chainable)' },
    { group: 'Terminal action', title: 'Terminal actions (exactly one)' },
    { group: 'Result accessor', title: 'The result' },
    { group: 'Golden', title: 'Goldens' },
    { group: 'Time & doubles', title: 'Primitives' },
];

/** What a card says before its tables — the part that is this kind's alone. */
type CardHead = {
    chapter: string;
    /** The line that builds the runner, or what stands in for it. */
    constructs: string;
    /** Where the test file goes. */
    livesAt: string;
    /** The one-sentence question this kind answers. */
    specifies: string;
    title: string;
    /** What this kind refuses, and where that case goes instead. */
    refuses: string;
    /** The vitest project that collects it. */
    project: string;
    /** Groups this kind does not publish, each with the reason a reader owes. */
    silent?: Partial<Record<CapabilityGroup, string>>;
    /** Whether {@link CardHead.constructs} is code, or a sentence saying there is none. */
    started: boolean;
};

const HEADS: Record<Kind, CardHead> = {
    api: {
        chapter: '10-api.md',
        constructs: [
            "import { postgres, specification } from '@jterrazz/test';",
            '',
            'export const { api, cleanup } = await specification.api({',
            "    server: () => ({ request: () => new Response('ok') }),",
            '    services: { main: postgres() },',
            '});',
        ].join('\n'),
        livesAt: '`specs/api/<domain>/<aspect>.spec.ts`',
        project: 'api()',
        refuses:
            'A handler called directly is a module test; a repository against a real database with no HTTP is an integration spec.',
        specifies:
            'Given this state and this request, what does the HTTP app answer, and what does it leave behind?',
        started: true,
        title: 'API specs',
    },
    cli: {
        chapter: '12-cli.md',
        constructs: [
            "import { specification } from '@jterrazz/test';",
            '',
            "export const { cli, cleanup } = await specification.cli('./bin/shoply.sh', {",
            "    defaults: { NO_COLOR: '1', TZ: 'UTC' },",
            '});',
        ].join('\n'),
        livesAt: '`specs/cli/<domain>/<case>.spec.yaml` (the default door) or `<aspect>.spec.ts`',
        project: 'cli()',
        refuses:
            'An imported function is a module test — the subject here is the built binary in a child process.',
        specifies:
            'Given this file tree, this environment and this argv, what does the binary print, exit with, and leave on disk?',
        started: true,
        title: 'CLI specs',
    },
    component: {
        chapter: '07-component.md',
        constructs: [
            "import { component, content } from '@jterrazz/test';",
            '',
            'export const result = await component.render(',
            '    (container) => {',
            "        container.textContent = 'Showing 1 of 200 posts';",
            '    },',
            '    async (visitor) => {',
            "        await visitor.see(content('Showing 1 of 200 posts'));",
            '    },',
            ');',
        ].join('\n'),
        livesAt: '`<file>.test.tsx` beside `<file>.tsx` — there is no facet folder',
        project: 'component()',
        refuses:
            'A whole served page is a website spec; a React Native screen stays on jest until the react-native-web spike says otherwise.',
        specifies:
            'Given this network and this parent, what does the component put on the screen, and what does it report back?',
        started: false,
        title: 'Component specs',
    },
    integration: {
        chapter: '06-integration.md',
        constructs: [
            "import { specification, sqlite } from '@jterrazz/test';",
            '',
            'export const { cleanup, integration } = await specification.integration({',
            '    services: { main: sqlite() },',
            '});',
        ].join('\n'),
        livesAt: '`specs/integration/<domain>/<aspect>.spec.ts`',
        project: 'integration()',
        refuses:
            'A module with no real service and no golden needs no runner at all — that is a module test.',
        specifies:
            'Given real services or a golden oracle, what does this module return, and what does it write?',
        started: true,
        title: 'Integration specs',
    },
    jobs: {
        chapter: '11-jobs.md',
        constructs: [
            "import { specification } from '@jterrazz/test';",
            '',
            'export const { cleanup, jobs } = await specification.jobs({',
            "    jobs: [{ execute: async () => {}, name: 'daily-digest' }],",
            '});',
        ].join('\n'),
        livesAt: '`specs/jobs/<domain>/<aspect>.spec.ts`',
        project: 'jobs()',
        refuses:
            'A pure function inside the pipeline is a module test; the pipeline met through its name is this.',
        specifies:
            'When this name is triggered, what does the pipeline do to the world it was handed?',
        started: true,
        title: 'Jobs specs',
    },
    mobile: {
        chapter: '09-mobile.md',
        constructs: [
            "import { specification } from '@jterrazz/test';",
            '',
            'export const { cleanup, mobile } = await specification.mobile({',
            "    app: { bundleId: 'com.example.app' },",
            "    device: { name: 'iPhone 17' },",
            '});',
        ].join('\n'),
        livesAt: '`specs/mobile/<domain>/<aspect>.spec.ts`',
        project: 'mobile()',
        refuses:
            "A component rendered off a device is jest's for now — this facet drives an installed app on a simulator.",
        specifies:
            'Given this backend and this visitor, what does the native app draw, and how does the screen read?',
        started: true,
        title: 'Mobile specs',
    },
    module: {
        chapter: '05-module-tests.md',
        constructs:
            'Nothing is started: a plain `test()` beside the module, reaching for the primitives below.',
        livesAt: '`<file>.test.ts` beside `<file>.ts` — there is no facet folder',
        project: 'unit()',
        refuses:
            'A golden, a real service, a DOM, a data asset, `vi.mock` outside the allow-list, `vi.stubGlobal` — each has a kind that owns it.',
        silent: {
            Golden: 'a module test may not carry a golden (rule D20) — a module whose answer deserves one is an integration spec',
        },
        specifies:
            'Given these inputs and these ports, what does this module return, and what does it ask of its collaborators?',
        started: false,
        title: 'Module tests',
    },
    website: {
        chapter: '08-website.md',
        constructs: [
            "import { specification } from '@jterrazz/test';",
            '',
            'export const { cleanup, website } = await specification.website({',
            "    server: { command: 'npm run preview', ready: '/' },",
            '});',
        ].join('\n'),
        livesAt: '`specs/website/<domain>/<aspect>.spec.ts`',
        project: 'website()',
        refuses:
            'One rendered unit inside the page is a component spec; the loader behind it is a module test.',
        specifies:
            'Given this backend and this visitor, what does the served site show, and what does it report to the console?',
        started: true,
        title: 'Website specs',
    },
};

/** The capabilities of one group that a column declares, in declaration order. */
function capabilitiesOf(kind: Kind, group: CapabilityGroup): string[] {
    return CAPABILITIES.filter(
        (capability) => capability.group === group && capability.columns.includes(kind),
    ).map((capability) => capability.name);
}

/** Every capability name the cards must describe. */
export function coveredGroups(): CapabilityGroup[] {
    return SECTIONS.map((section) => section.group);
}

/** Capability names of a rendered group that {@link SIGNATURES} does not describe. */
export function uncoveredCapabilities(): string[] {
    const groups = new Set<CapabilityGroup>(coveredGroups());
    return CAPABILITIES.filter(
        (capability) => groups.has(capability.group) && !(capability.name in SIGNATURES),
    ).map((capability) => capability.name);
}

/** Entries of {@link SIGNATURES} that no capability claims any more. */
export function deadSignatures(): string[] {
    const declared = new Set(CAPABILITIES.map((capability) => capability.name));
    return Object.keys(SIGNATURES).filter((name) => !declared.has(name));
}

/** A list of names as one line of inline code. */
function quoted(names: string[]): string {
    return names.map((name) => `\`${name}\``).join(' · ');
}

/** The element vocabulary a kind reaches, as two sentences — chapter 13 owns the words. */
function vocabulary(kind: Kind): string[] {
    const verbs = capabilitiesOf(kind, 'Verb');
    const descriptors = capabilitiesOf(kind, 'Descriptor');
    if (verbs.length === 0 && descriptors.length === 0) {
        return [];
    }
    return [
        '## The vocabulary',
        '',
        `The visitor's verbs: ${quoted(verbs)}.`,
        '',
        `The descriptors, landmarks and modifiers: ${quoted(descriptors)}.`,
        '',
        'All of them are defined once, in [13 — Elements](../../../docs/13-elements.md): the same words, the same W3 refusal, the same exact-by-default matching, on every surface that draws.',
    ];
}

/** One section of a card — a table of `signature | line`, or nothing if the kind has none. */
function sectionOf(kind: Kind, group: CapabilityGroup, title: string): string[] {
    const silent = HEADS[kind].silent?.[group];
    if (silent !== undefined) {
        return [`## ${title}`, '', `None here: ${silent}.`];
    }
    const names = capabilitiesOf(kind, group);
    if (names.length === 0) {
        return [];
    }
    const rows = names.map((name) => {
        const found = SIGNATURES[name];
        return [`\`${name}\``, cell(`\`${found?.signature ?? name}\``), cell(found?.line ?? '')];
    });
    return [`## ${title}`, '', ...table(['Name', 'Written', 'Does'], rows)];
}

/**
 * How a card shows the line a test opens on. A kind that STARTS something says
 * "constructed"; one that starts nothing says "written as", because there is no
 * runner to construct — and the kind that opens on nothing at all says so in a
 * sentence rather than in an empty fence.
 */
function constructed(head: CardHead): string {
    const label = head.started ? '**Constructed with**' : '**Written as**';
    if (!head.constructs.includes('\n')) {
        return `${label} — ${head.constructs}`;
    }
    return [label, '', '```typescript', head.constructs, '```'].join('\n');
}

/** One signature card — `skills/jterrazz-test/references/<kind>.md`. */
export function renderCard(kind: Kind): string {
    const head = HEADS[kind];
    const parts = [
        CARD_HEADER,
        `# \`@jterrazz/test\` — ${head.title}`,
        `> Generated from \`src/lint/cards.ts\` and the facet declaration by \`npm run docs\`. The chapter is [${head.chapter}](../../../docs/${head.chapter}).`,
        `**Specifies** — ${head.specifies}`,
        `**Lives at** — ${head.livesAt}`,
        `**Collected by** — \`${head.project}\` in \`vitest.config.ts\``,
        constructed(head),
        `**Not this kind** — ${head.refuses}`,
    ];
    for (const { group, title } of SECTIONS) {
        const body = sectionOf(kind, group, title);
        if (body.length > 0) {
            parts.push(body.join('\n'));
        }
    }
    const words = vocabulary(kind);
    if (words.length > 0) {
        parts.push(words.join('\n'));
    }
    parts.push(
        [
            '## Read next',
            '',
            `The chapter: [${head.chapter}](../../../docs/${head.chapter}). The fork: [fork.md](fork.md). What the package proves on each capability: [matrix.md](matrix.md). The rules that judge this file: [rules.md](rules.md).`,
        ].join('\n'),
    );
    return `${parts.join('\n\n')}\n`;
}

/** The fork table itself — the same rows in the chapter and in the card. */
function forkTable(): string[] {
    return table(
        ['Question', 'Kind', 'Lives at', 'Constructor', 'Project'],
        FORK.map((row) => [
            cell(row.question),
            row.kind,
            cell(row.livesAt),
            cell(row.constructor),
            cell(row.project),
        ]),
    );
}

/** Replace the region between the GENERATED markers of chapter 18 with a fresh fork table. */
export function spliceFork(existing: string): string {
    const start = existing.indexOf(FORK_START);
    const end = existing.indexOf(FORK_END);
    if (start === -1 || end === -1) {
        throw new Error(
            `docs/18-conventions.md is missing the GENERATED:fork markers (${FORK_START} … ${FORK_END})`,
        );
    }
    const inner = [FORK_START, '', ...forkTable(), '', FORK_END].join('\n');
    return existing.slice(0, start) + inner + existing.slice(end + FORK_END.length);
}

/** The agent-facing fork — `skills/jterrazz-test/references/fork.md`. */
export function renderFork(): string {
    const parts = [
        CARD_HEADER,
        '# `@jterrazz/test` — the fork',
        '> Generated from `src/lint/cards.ts` by `npm run docs`. Ask the questions IN ORDER; the first yes is the kind. The constitution is [18 — Conventions](../../../docs/18-conventions.md).',
        forkTable().join('\n'),
        [
            'The fork is the SUBJECT, never the amount of machinery: a rendered component needs a browser, a pipeline, a network double and a golden engine and is still a unit, so it sits beside its code; a module that needs a real database needs nothing new and is still an assembled thing, so it sits under `specs/`.',
            '',
            'The SUFFIX says the kind and the checker holds it (rule C12): `.test.ts(x)` beside the code, `.spec.ts` under `specs/<facet>/`, `<case>.spec.yaml` for a literate document, `<facet>.specification.ts` for the file that builds a runner.',
        ].join('\n'),
        [
            '## The card of each kind',
            '',
            ...KINDS.map((kind) => `- ${HEADS[kind].title} — [${kind}.md](${kind}.md)`),
        ].join('\n'),
    ];
    return `${parts.join('\n\n')}\n`;
}
