import { catalog, FAMILIES } from './manifest.js';
import type { CatalogEntry } from './manifest.js';

/**
 * The conventions-catalogue generator — renders the mechanized rule catalogue
 * FROM `manifest.ts` (the source of truth) into two committed projections:
 *
 * - the full seven-channel catalogue inside `docs/13-linting.md`, spliced between
 *   GENERATED markers ({@link spliceCatalog}) — grouped by convention family,
 *   each row anchored by its implementation name so a rule MESSAGE can link
 *   straight to it, and carrying what it REACHES and the one imperative line
 *   that FIXES it where the row states them (a ban with no destination is an
 *   argument, not a rule);
 * - `skills/jterrazz-test/references/rules.md` — the agent-facing rule reference
 *   ({@link renderRules}).
 *
 * Output is deterministic (the manifest is pre-sorted), so `plugin.test.ts` can
 * assert freshness: running the generator must reproduce the committed files
 * byte-for-byte. `catalog-cli.ts` (bundled as `dist/catalog.js`) writes them;
 * `npm run docs` chains it alongside `typescript docs`, which regenerates the
 * `docs/reference/` projection.
 */

/** Markers delimiting the generated catalogue inside `docs/13-linting.md`. */
export const DOCS_START =
    '<!-- GENERATED:catalog — do not edit by hand; run `npm run docs`. Source: src/lint/manifest.ts -->';
export const DOCS_END = '<!-- /GENERATED:catalog -->';

/** First-line header stamped on the generated skill reference `rules.md`. */
export const RULES_HEADER = "<!-- GENERATED by 'npm run docs' — DO NOT EDIT -->";

/** Escape a markdown table cell (pipes would split the row). */
export function cell(text: string): string {
    return text.replaceAll('|', String.raw`\|`);
}

/**
 * Render a GitHub-flavoured markdown table the way oxfmt (prettier) canonicalizes
 * one: each column padded to its widest cell (min 3). Emitting this form keeps the
 * generated files format-clean, so the freshness meta-test and the formatter agree.
 * All cell characters are BMP width-1 (Latin, arrows, curly quotes), so
 * `String.length` equals the display width.
 */
export function table(headers: string[], rows: string[][]): string[] {
    const widths = headers.map((header, index) =>
        Math.max(header.length, 3, ...rows.map((row) => (row[index] ?? '').length)),
    );
    const line = (cells: string[]): string =>
        `| ${cells.map((text, index) => text.padEnd(widths[index] ?? 0)).join(' | ')} |`;
    const separator = `| ${widths.map((width) => '-'.repeat(width)).join(' | ')} |`;
    return [line(headers), separator, ...rows.map(line)];
}

/**
 * How the channels are ordered inside a family's table: the ones a reader can
 * run first, then the ones the framework raises, then the judgement.
 */
const CHANNEL_ORDER: Record<CatalogEntry['channel'], number> = {
    statique: 0,
    upstream: 1,
    checker: 2,
    runtime: 3,
    type: 4,
    meta: 5,
    process: 6,
};

/**
 * The landing spot a rule MESSAGE links to.
 *
 * A message ending in `docs/13-linting.md#<implementation>` is only a route if
 * something in the file answers to that fragment, and a table row is not a
 * heading. The anchor rides inside the Implementation cell, where it renders as
 * nothing and resolves as the row.
 */
export function anchor(name: string): string {
    return `<a id="${name}"></a>`;
}

/** The catalogue families of a set of rows, deterministically ordered. */
function families(rows: CatalogEntry[]): string[] {
    return [...new Set(rows.map((entry) => entry.family))].sort((a, b) => a.localeCompare(b));
}

/**
 * How the catalogue is grouped: `core` first — the rules that reach every
 * facet, which is what a reader adopting ANY facet owes — then one section per
 * facet, alphabetically.
 *
 * A reader adopting one constructor should be able to stop reading at the end
 * of two sections. Grouping by family alone could not say that: a family is a
 * kind of convention, not an audience, and `C — Files & folders` mixes a rule
 * every facet obeys with one only the literate door can break.
 */
const FACET_ORDER = ['core', 'api', 'cli', 'component', 'integration', 'jobs', 'mobile', 'website'];

/** The facet sections present in the catalogue, core first. */
function facets(): string[] {
    const present = new Set<string>(catalog.map((entry) => entry.facet));
    return FACET_ORDER.filter((facet) => present.has(facet));
}

/** What a facet section is titled — the tree, and what it is the tree of. */
const FACET_TITLES: Record<string, string> = {
    api: 'the HTTP app, met through its entry',
    cli: 'the command binary and its literate documents',
    component: 'a rendered unit, in a page',
    core: 'every facet, whichever constructor you reach for',
    integration: 'a module against the real thing',
    jobs: 'what a name triggers in-process',
    mobile: 'a native screen on a simulator',
    website: 'the served site, driven in a browser',
};

/** Per-channel row counts, for the generated intro line. */
function counts(): Record<CatalogEntry['channel'], number> {
    const tally: Record<CatalogEntry['channel'], number> = {
        checker: 0,
        meta: 0,
        process: 0,
        runtime: 0,
        statique: 0,
        type: 0,
        upstream: 0,
    };
    for (const entry of catalog) {
        tally[entry.channel] += 1;
    }
    return tally;
}

/**
 * The catalogue's sections: `## <facet>` — core first — each holding one
 * `### <family> — <title>` table (Code · Implementation · Channel · Reach ·
 * Convention · Fix · Rationale) sorted by channel then id.
 */
function catalogueSections(): string[] {
    return facets().flatMap((facet) => {
        const owned = catalog.filter((entry) => entry.facet === facet);
        const tables = families(owned).map((family) => {
            const rows = owned
                .filter((entry) => entry.family === family)
                .sort((a, b) => CHANNEL_ORDER[a.channel] - CHANNEL_ORDER[b.channel])
                .map((entry) => [
                    entry.id,
                    `${anchor(entry.name)}\`${entry.name}\``,
                    entry.channel,
                    entry.reach,
                    cell(entry.convention),
                    cell(entry.fix),
                    cell(entry.rationale),
                ]);
            return [
                `### ${family} — ${FAMILIES[family] ?? family}`,
                '',
                ...table(
                    [
                        'Code',
                        'Implementation',
                        'Channel',
                        'Reach',
                        'Convention',
                        'Fix',
                        'Rationale',
                    ],
                    rows,
                ),
            ].join('\n');
        });
        tables.unshift(`## ${facet} — ${FACET_TITLES[facet] ?? facet}`);
        return tables;
    });
}

/**
 * The full seven-channel catalogue spliced into `docs/13-linting.md` between the
 * GENERATED markers — a counts line, then every family section. The surrounding
 * chapter prose is hand-maintained; only this region is generated.
 */
function renderDocsCatalog(): string {
    const c = counts();
    // The channels with rows are the ones named; one that has none yet is not
    // Announced with a zero, because a reader would go looking for it.
    const named = [
        [c.statique, '**statique** (oxlint rules)'],
        [c.upstream, '**upstream** (options set on an upstream rule)'],
        [c.checker, '**checker** (bundled passes)'],
        [c.runtime, '**runtime** (execution-time refusals)'],
        [c.type, '**type** (what the compiler refuses)'],
        [c.meta, '**meta** (what a meta-test holds)'],
        [c.process, '**process** (review-borne rules)'],
    ] as const;
    const channels = named
        .filter(([count]) => count > 0)
        .map(([count, label]) => label.replace(' (', ` — ${String(count)} (`))
        .join(', ');
    const intro = `Every rule the framework enforces, across its enforcement channels — ${channels} — sourced from one manifest so the code and the catalogue can never drift.`;
    const inner = [intro, ...catalogueSections()].join('\n\n');
    return `${DOCS_START}\n\n${inner}\n\n${DOCS_END}`;
}

/** Replace the region between the GENERATED markers of `docs/10` with a fresh catalogue. */
export function spliceCatalog(existing: string): string {
    const start = existing.indexOf(DOCS_START);
    const end = existing.indexOf(DOCS_END);
    if (start === -1 || end === -1) {
        throw new Error(
            `docs/13-linting.md is missing the GENERATED:catalog markers (${DOCS_START} … ${DOCS_END})`,
        );
    }
    return existing.slice(0, start) + renderDocsCatalog() + existing.slice(end + DOCS_END.length);
}

/**
 * The agent-facing rule reference `skills/jterrazz-test/references/rules.md` —
 * the same seven-channel catalogue as `docs/13`, trimmed to what an agent needs
 * to apply and cite a rule (Code · Implementation · Channel · Enforces), grouped
 * core first, then by facet, then by family. Stamped `DO NOT EDIT`; the skill routes here for rule ids.
 */
export function renderRules(): string {
    const sections = facets().flatMap((facet) => {
        const owned = catalog.filter((entry) => entry.facet === facet);
        const tables = families(owned).map((family) => {
            const rows = owned
                .filter((entry) => entry.family === family)
                .sort((a, b) => CHANNEL_ORDER[a.channel] - CHANNEL_ORDER[b.channel])
                .map((entry) => [
                    entry.id,
                    `\`${entry.name}\``,
                    entry.channel,
                    cell(entry.convention),
                    cell(entry.fix),
                ]);
            const body = table(['Code', 'Implementation', 'Channel', 'Enforces', 'Fix'], rows).join(
                '\n',
            );
            return `### ${family} — ${FAMILIES[family] ?? family}\n\n${body}`;
        });
        tables.unshift(`## ${facet} — ${FACET_TITLES[facet] ?? facet}`);
        return tables;
    });

    const parts = [
        RULES_HEADER,
        '# `@jterrazz/test` — rule reference',
        '> Generated from `src/lint/manifest.ts` by `npm run docs` — every mechanized convention across the seven enforcement channels (statique · upstream · checker · runtime · type · meta · process). Rule ids are stable: cite them in suppressions and reviews. Narrative lives in `docs/12-conventions.md` (the constitution) and `docs/13-linting.md` (the static plugin + checker).',
        ...sections,
    ];
    return `${parts.join('\n\n')}\n`;
}
